### ISSUE TITLE
Using tanh and NPE in ClassModel

### ISSUE THREAD

**Issue by stoerr** [aparapi/aparapi#15]
I was trying to use tanh by declaring

    @OpenCLMapping(mapTo = "tanh")
    protected float tanh(float _f) {
        return (float) Math.tanh(_f);
    }

Unfortunately, this exposes a NullPointerException:

java.lang.NullPointerException
	at com.amd.aparapi.internal.model.ClassModel.parse(ClassModel.java:2542)
	at com.amd.aparapi.internal.model.ClassModel.parse(ClassModel.java:2526)
	at com.amd.aparapi.internal.model.ClassModel.<init>(ClassModel.java:142)

The problem is, that it tries to parse java.lang.Math, and Math.class.getClassLoader() returns null, so the ClassModel can't find the class file. I'm not quite sure how aparapi should deal with this - perhaps classes used in methods annotated with @OpenCLMapping shouldn't be parsed at all.

It would be nice, too, if the Kernel would define tanh and similar methods, anyway.

Thanks so much!

**Comment by stoerr** [comment]
Also, the @OpenCLMapping doesn't seem to have any effect on the generated code. As a workaround, I used

    @OpenCLMapping(mapTo = "tanh")
    protected float tanh(float _f) {
        float epx = exp(_f);
        float enx = exp(-_f);
        return (epx - enx) / (epx + enx);
    }

and expected this to translate to the OpenCL tanh function, but the whole function is translated to OpenCL as is.

**Comment by grfrost** [comment]
Were you adding this to the source of Kernel.java in the aparapi code
tree?  Or your subclass?

**Comment by stoerr** [comment]
I was using a subclass. I assume it would have worked if I changed and built aparapi myself.

**Comment by Ryan-LaMothe-PNNL** [comment]
Is this still an issue with the latest Trunk code?

**Comment by stoerr** [comment]
Unfortunately I couln't build it, since there was an error:

C:\R\GitHub\aparapi\com.amd.aparapi\src\java\com\amd\aparapi\device\Device.java:165: error: no suitable method found for hashCode(long)
      return Long.hashCode(getDeviceId());
                 ^
    method Long.hashCode() is not applicable
      (actual and formal argument lists differ in length)
    method Object.hashCode() is not applicable
      (actual and formal argument lists differ in length)

Which seems strange, since there is no Long.hashCode(long) in either JDK7 or 8.

Anyway, is there a nightly build or something to download, which I could try?

**Comment by freemo** [comment]
This issue was moved to Syncleus/aparapi#6

**Comment by rlamothe** [comment]
@stoerr The latest Aparapi source code is building now on Java 8. Are you still interesting in re-attempting this work?
