### ISSUE TITLE
Single sequential execution reports error

### ISSUE THREAD

**Issue by dlippold** [aparapi/aparapi#43]
When I execute the example "add" (on Linux with JDK 7) in the single sequential Java loop, set by the property "-Dcom.amd.aparapi.executionMode=SEQ", I get the following error message:

> Exception in thread "main" java.lang.IllegalStateException: Can't run range with group size >1 sequentially. Barriers would deadlock!
> 	at com.amd.aparapi.internal.kernel.KernelRunner.executeJava(KernelRunner.java:242)
> 	at com.amd.aparapi.internal.kernel.KernelRunner.execute(KernelRunner.java:1196)
> 	at com.amd.aparapi.Kernel.execute(Kernel.java:2028)
> 	at com.amd.aparapi.Kernel.execute(Kernel.java:1962)
> 	at com.amd.aparapi.Kernel.execute(Kernel.java:1933)
> 	at com.amd.aparapi.sample.add.Main.main(Main.java:67)

Steps to reproduce on Linux:

1. "java -version" gives "OpenJDK Runtime Environment (IcedTea 2.6.7) (7u111-2.6.7-2~deb7u1)
OpenJDK 64-Bit Server VM (build 24.111-b01, mixed mode)"
2. mkdir Aparapi
3. cd Aparapi
4. unzip ~/dist_linux_x86_64.zip
5. cd samples/add/
6. java -Djava.library.path=../..  -classpath ../../aparapi.jar:add.jar -Dcom.amd.aparapi.executionMode=SEQ com.amd.aparapi.sample.add.Main

**Comment by SubaruWRC** [comment]
I believe that is the correct behavior with SEQ mode. Does the example work correctly in JTP mode?

**Comment by dlippold** [comment]
Yes, the example work correctly in JTP mode.

But
1. there is no usage of barrier in the example.
2. And even if there would be one, how should a single execution thread deadlock?
3. Every program should be executable sequentially (if not, the conversion to OpenCL is broken).

**Comment by grfrost** [comment]
Actually the complaint is that you are asking to execute sequentially but
with a group size >1.   You can't expect this to work.

Either you want seq or you don't

The comment about barrier is true.  If you had a barrier and we let groups
> 1 execute then barriers would indeed deadlock because single thread would
block (cyclic barrier) waiting for other 'threads' to join, which they
would not.

How is the kernel being launched? My guess is you are asking for group size
> 1.

Gary

**Comment by dlippold** [comment]
I assume the quotes in the last comment are done unintended.

My understanding of "group size" is that it is the number of work-items in a work-group, executed by threads which can be synchronized by a barrier and which are executed by the same compute unit.

Why should it not be possible to execute more than one work-item (of a work-group) sequentially (by only one thread)? The work-items should be executed one by one.

From my understanding a single thread can never deadlock because a deadlock needs more than one thread so that the threads block each other.

All I did is described in the first text above. Therefore I didn't asked for any group size on the command line.  In the Main class there is the following instruction:

`kernel.execute(Range.create(512));`

Therefore the desision about the groups size was done by the aparapi compiler and if that desision leads to problems for a sequential execution (even it should not be the case) that decision from the aparapi compiler may be wrong.

**Comment by SubaruWRC** [comment]
Thank you for reporting this. A few quick things regarding this ticket:

1) Can you manually set the group size to 1 and see if it resolves the issue?

2) If it does, can you please clone the aparapi repository, debug the issue and if a bug is found please write the code to correct the issue and submit a pull request? There have been a couple of threads over the years on optimizations to the JTP code and now with Java 8, it might be time to overhaul the JTP code to just use Lambda’s (or another similar solution).


Thanks!

---
Ryan LaMothe

**Comment by dlippold** [comment]
To 1)
Yes, when I replace the line

`kernel.execute(Range.create(512));`

in the Main class by

`kernel.execute(Range.create(512, 1));`

the execution in single sequential execution works without error. When I change it to

`kernel.execute(Range.create(512, 2));`

the error is back again.

To 2)
The problem occurs with "SEQ" as method of execution, not with "JTP".

Because I don't know the Aparapi code it would be a great effort to become acquainted with it to fix the bug in the right way. And because I currently don't use Aparapi for production I don't have the time to fix it.

**Comment by rlamothe** [comment]
I apologize for the typo, I meant SEQ instead of JTP. Were you intending to use SEQ mode for debugging purposes?

**Comment by dlippold** [comment]
Do you mean the type in the last article from SubaruWRC? Do belong both account to you?

In principle I wanted to use SEQ for debugging and for runtime comparision. But in my tests it was not really necessary to use it.

**Comment by rlamothe** [comment]
Yes, sorry for the confusion, I plan to merge both accounts.
